select *
from customer
limit 20

-- What is the total revenue generated by male vs female customers?
select
	gender,
	sum(purchase_amount) as "Total Revenue Generated"
from customer
group by gender

-- Which customers used a discount but still spent more than the average purchase amount?

select
	customer_id,
	purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- Which are the top 5 products with the highest average review rating?
select
	item_purchased,
	round(avg(review_rating :: numeric), 2) as "Average Review Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select
	shipping_type,
	round(avg(purchase_amount),2) as "Average Purchase Amount"
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select
	count(customer_id) as "Number of Customers",
	subscription_status,
	round(avg(purchase_amount), 2) as "Average Spend",
	round(sum(purchase_amount), 2) as "Total Revenue"
from customer
group by subscription_status
order by avg(purchase_amount) desc


-- Which 5 products have the highest percentage of purchases with discounts applied?
select
	item_purchased,
	round(sum(case when discount_applied = 'Yes' THEN 1 else 0 end) :: numeric/ count(*), * 100, 2) as "Percentage of Purchases"
	-- We are trying to calculate the percentage of purchases as that's something we want, accourding to the question
	-- We are also type casting ":: numeric" just to be on the safer side.
from customer
group by item_purchased
order by "Percentage of Purchases"
limit 5


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segement.
with customer_type as (
select
	customer_id,
	previous_purchases,
	case
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
		end as customer_segment
		-- BY using the case statements we are seperating the previous purchases into 3 segments, by comparing the previous_purchases values with our assigned values.
from customer
)
select
	customer_segment,
	count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- For the above question we solved using Common Table Expression (CTE), as we are creating a virtual table, which will help us to sort the customers based on the criteria.
-- Our CTE is named as customer_type and by using Case statements we are distinguishing the customer type. But CTE is supposed to be enclosed within brackets.



-- What are the top 3 most purchased products within each category
"select
	item_purchased,
	category,
	count(customer_id) as total_orders
from customer
group by item_purchased, category
limit 3"
-- The above line of code gives us the top 3 products from across all the category. Which satisfies the question only half way through.


with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
	count(customer_id) as "Number of Customer",
	subscription_status
from customer
where previous_purchases > 5
group by subscription_status
	

-- What is the revenue contribution by Age group
select
	age_group,
	sum(purchase_amount) as "Revenue Contribution"
from customer
group by age_group
order by sum(purchase_amount) desc
